services:
  zero:
    image: dgraph/dgraph:v24.0.5 # Use a specific version for reproducibility
    volumes:
      - dgraph-data:/dgraph  # Named volume for persistence
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure  # Automatically restart if the container fails
    command: dgraph zero --my=zero:5080 --bindall=true

  alpha:
    image: dgraph/dgraph:v24.0.5 # Use a specific version
    volumes:
      - dgraph-data:/dgraph  # Use the same named volume
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    depends_on:
      - zero
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --bindall=true

  ratel: # Optional: Dgraph's UI
    image: dgraph/ratel:v21.03.0 #Match Ratel version to dgraph version
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - alpha

volumes:
  dgraph-data: # Define the named volume